import React, { FunctionComponent } from "react";
import Head from "next/head";

import Nav from "components/Nav";
import Footer from "components/Footer";
import styles from "./Layout.module.scss";

type ILayoutProps = {
  children: any;
};

const Layout: FunctionComponent<ILayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className={styles.Layout__main}>{children}</main>
      <Footer />
    </>
  );
};

export default Layout;
