import React, { useContext, FunctionComponent } from "react";
import Head from "next/head";

import Nav from "components/Nav";
import Footer from "components/Footer";
import Dialog from "components/Dialog";
import { DialogManagerContext } from "contexts/DialogManagerContext";
import styles from "./Layout.module.scss";

type ILayoutProps = {
  children: any;
};

const Layout: FunctionComponent<ILayoutProps> = ({ children }) => {
  const { dialogComponent, dialogProps } = useContext(DialogManagerContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className={styles.Layout__main}>{children}</main>
      <Footer />

      <Dialog
        open={!!dialogComponent}
        title={dialogProps?.title}
        content={dialogComponent}
        onPrimaryBtnClick={dialogProps?.onPrimaryBtnClick}
        onSecondaryBtnClick={dialogProps?.onSecondaryBtnClick}
      />
    </>
  );
};

export default Layout;
